[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 3;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = jtaghub16_jtck;
GLOBAL_PRIMARY_0_DRIVERTYPE = JTAG;
GLOBAL_PRIMARY_0_LOADNUM = 149;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = Clk_N;
GLOBAL_PRIMARY_1_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_1_LOADNUM = 125;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = Clk_FPGA_c;
GLOBAL_PRIMARY_2_DRIVERTYPE = PIO;
GLOBAL_PRIMARY_2_LOADNUM = 14;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 2;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = top_reveal_coretop_instance/reset_n_N_112;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 114;
GLOBAL_SECONDARY_0_SIGTYPE = RST;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = jtaghub16_jrstn;
GLOBAL_SECONDARY_1_DRIVERTYPE = JTAG;
GLOBAL_SECONDARY_1_LOADNUM = 142;
GLOBAL_SECONDARY_1_SIGTYPE = RST;
; I/O Bank 0 Usage
BANK_0_USED = 0;
BANK_0_AVAIL = 60;
BANK_0_VCCIO = NA;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
BANK_0_VTT = ;
; I/O Bank 1 Usage
BANK_1_USED = 0;
BANK_1_AVAIL = 48;
BANK_1_VCCIO = NA;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
BANK_1_VTT = ;
; I/O Bank 2 Usage
BANK_2_USED = 0;
BANK_2_AVAIL = 42;
BANK_2_VCCIO = NA;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
BANK_2_VTT = ;
; I/O Bank 3 Usage
BANK_3_USED = 1;
BANK_3_AVAIL = 71;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
BANK_3_VREF2 = NA;
BANK_3_VTT = ;
; I/O Bank 6 Usage
BANK_6_USED = 3;
BANK_6_AVAIL = 79;
BANK_6_VCCIO = 3.3V;
BANK_6_VREF1 = NA;
BANK_6_VREF2 = NA;
BANK_6_VTT = ;
; I/O Bank 7 Usage
BANK_7_USED = 1;
BANK_7_AVAIL = 56;
BANK_7_VCCIO = 3.3V;
BANK_7_VREF1 = NA;
BANK_7_VREF2 = NA;
BANK_7_VTT = ;
; I/O Bank 8 Usage
BANK_8_USED = 1;
BANK_8_AVAIL = 24;
BANK_8_VCCIO = 3.3V;
BANK_8_VREF1 = NA;
BANK_8_VREF2 = NA;
BANK_8_VTT = ;
