-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.7
-- Tue Jan 26 07:37:03 2021

-- parameterized module component declaration
component PLL_2
    port (CLK: in std_logic; CLKOP: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : PLL_2
    port map (CLK=>__, CLKOP=>__, LOCK=>__);
