-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.7
-- Mon Jan 25 14:27:30 2021

-- parameterized module component declaration
component PLL_IP
    port (CLK: in std_logic; CLKOP: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : PLL_IP
    port map (CLK=>__, CLKOP=>__, LOCK=>__);
